# Generated by Django 5.2.1 on 2025-05-13 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_message_edited'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('requested_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.skilllisting')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_agreements', to=settings.AUTH_USER_MODEL)),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_agreements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
